[project]
name = 'sw-vault'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP120SBRBQJ00MCWS7TM5R8WJNTTKD5K0HFRC2CNE.usdcx'

[contracts.sponsored-usdcx-vault]
path = 'contracts/sponsored-usdcx-vault.clar'
clarity_version = 3
epoch = 'latest'

[contracts.usdcx-token]
path = 'contracts/usdcx-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.usdcx-vault]
path = 'contracts/usdcx-vault.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
